title: City Design Project
description: Exploring city design through algorithms.
theme: jekyll-theme-hyde
baseurl: "" # Leave empty for GitHub Pages
url: "https://<your-username>.github.io/city-design-website"

# Navigation Links
nav_links:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Project"
    url: "/project/"

# Social Links
twitter_username: your_twitter_username
github_username: your_github_username
